---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bananas-ingress
  namespace: fruits
spec:
  tls:
  - hosts:
    - bananas.fruits.app.pod1.lab
    secretName: bananas-ecdsa-cert
  rules:
  - host: bananas.fruits.app.pod1.lab
    http:
      paths:
      - path: /
        backend:
          serviceName: apples
          servicePort: 80
